artifact_root: artifact


data_ingestion:
  root_dir: artifact/data_ingestion
  source_URL: https://github.com/harcuracy/wine_repo/raw/refs/heads/main/archive.zip
  local_data_file: artifact/data_ingestion/data.zip
  unzip_dir: artifact/data_ingestion



data_validation:
 root_dir: artifact/data_validation
 data_file: artifact/data_ingestion/WineQT.csv
 status: artifact/data_validation/status.txt

