artifact_root: artifact


data_ingestion:
  root_dir: artifact/data_ingestion
  source_URL: https://github.com/harcuracy/wine_repo/raw/refs/heads/main/archive.zip
  local_data_file: artifact/data_ingestion/data.zip
  unzip_dir: artifact/data_ingestion



data_validation:
 root_dir: artifact/data_validation
 data_file: artifact/data_ingestion/WineQT.csv
 status: artifact/data_validation/status.txt


data_transformation:
 root_dir: artifact/data_transformation
 input_file: artifact/data_ingestion/WineQT.csv


model_training:
 root_dir: artifact/model_training
 train_data_file: artifact/data_transformation/train.csv
 model_file: artifact/model_training/model.joblib

model_evaluation:
 root_dir: artifact/model_evaluation
 test_data_file: artifact/data_transformation/test.csv
 model_file: artifact/model_training/model.joblib
 report_file: artifact/model_evaluation/report.json
 mlflow_tracking_uri: https://dagshub.com/harcuracy/machine_learning_project.mlflow


